import type{DetectedTerm,ExtendedModerationLexicon,ModerationLexicon,ModerationSeverity}from"../schema";
import{withoutAccents,type NormalizedModerationText}from"./normalize-text";

type Term=ModerationLexicon["terms"][number];
function escapeRegex(value:string){return value.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&")}
function contextWindow(text:string,start:number,end:number){return text.slice(Math.max(0,start-45),Math.min(text.length,end+45))}
function findTerm(text:NormalizedModerationText,term:Term){const forms=[term.term,term.normalized_term,...term.variants].map(form=>withoutAccents(form.normalize("NFKC").toLocaleLowerCase("fr")));for(const form of[...new Set(forms)].sort((a,b)=>b.length-a.length)){if(!form)continue;const pattern=new RegExp(`(^|[^\\p{L}\\p{N}])(${escapeRegex(form)})(?=$|[^\\p{L}\\p{N}])`,"u");const match=pattern.exec(text.accentInsensitive);if(match){const start=match.index+match[1].length;return{start,end:start+match[2].length,matched:match[2]}}}return null}
function detected(term:Term,text:NormalizedModerationText):DetectedTerm|null{const match=findTerm(text,term);if(!match)return null;return{termId:term.id??term.slug,canonicalTerm:term.term,matchedText:text.normalized.slice(match.start,match.end),normalizedMatch:match.matched,tier:term.tier,start:match.start,end:match.end,defaultSeverity:term.default_severity as ModerationSeverity,maxContextualSeverity:term.max_contextual_severity as ModerationSeverity,riskCategories:term.risk_categories,triggerPolicy:term.trigger_policy,contextWindow:contextWindow(text.normalized,match.start,match.end),sourceIds:term.source_ids,allowedContexts:term.allowed_contexts,suspiciousContexts:term.suspicious_contexts,replacementSuggestions:term.replacement_suggestions,contextDependency:term.context_dependency,recommendedAction:term.recommended_action}}

export function detectLexicalTerms(text:NormalizedModerationText,core:ModerationLexicon,extended:ExtendedModerationLexicon){const result:DetectedTerm[]=[];for(const term of[...core.terms,...extended.terms]){if(term.tier==="extended"&&term.normalized_term==="question")continue;const match=detected(term,text);if(match)result.push(match)}return result.sort((a,b)=>a.start-b.start||b.normalizedMatch.length-a.normalizedMatch.length)}
