import { notFound } from "next/navigation";
import { requireActiveProfile } from "@/features/auth/authorization";
import { campaignReportSchema } from "@/features/sponsorship/schema";
import { z } from "zod";

const campaignSchema=z.object({campaign_id:z.uuid(),campaign_name:z.string(),question_id:z.uuid(),question_text:z.string(),status:z.string(),starts_at:z.iso.datetime(),ends_at:z.iso.datetime(),response_target:z.number().int(),total_responses:z.number().int()});
export default async function CampaignsPage(){const{supabase,profile}=await requireActiveProfile();if(profile.account_type!=="verified")notFound();const{data,error}=await supabase.rpc("get_owned_sponsor_campaigns");if(error)return <main className="p-5"><h1 className="title">Rapports sponsor</h1><div role="alert" className="error-state mt-5">Impossible de charger vos campagnes.</div></main>;const parsed=z.array(campaignSchema).safeParse(data??[]);if(!parsed.success)return <main className="p-5"><h1 className="title">Rapports sponsor</h1><div role="alert" className="error-state mt-5">Réponse de rapport invalide.</div></main>;
 const reports=await Promise.all(parsed.data.map(async campaign=>{const result=await supabase.rpc("get_sponsor_campaign_report",{requested_campaign_id:campaign.campaign_id});return{campaign,report:result.error?null:z.array(campaignReportSchema).safeParse(result.data??[])}}));
 return <main className="p-5"><h1 className="title">Rapports sponsor</h1><p className="body-copy mt-2">Uniquement des résultats agrégés de la communauté Ekoa. Aucun profil ni historique individuel n’est accessible.</p>{!reports.length?<div className="empty-state mt-6">Aucune campagne associée à votre organisation.</div>:<ul className="mt-6 space-y-5">{reports.map(({campaign,report})=><li key={campaign.campaign_id} className="rounded-3xl border border-black/10 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-xl font-bold">{campaign.campaign_name}</h2><span className="eyebrow">{campaign.status}</span></div><p className="mt-2 font-semibold">{campaign.question_text}</p><p className="mt-2 text-sm text-[var(--muted)]">{campaign.total_responses} / {campaign.response_target} réponses</p>{!report||!report.success?<div role="alert" className="error-state mt-4">Rapport indisponible.</div>:report.data[0]?.suppressed?<div className="empty-state mt-4">Résultats masqués jusqu’à 20 réponses afin de protéger la confidentialité.</div>:<ul className="mt-4 space-y-2">{report.data.map(row=><li key={row.option_text} className="flex justify-between rounded-2xl bg-[var(--background)] p-3"><span>{row.option_text}</span><strong>{row.vote_count} · {row.percentage} %</strong></li>)}</ul>}</li>)}</ul>}</main>}
