"use client";
import {useCallback,useEffect,useRef,useState,useTransition,type FormEvent} from "react";
import {ReportForm} from "@/features/reports/report-form";import type{CommentActionState}from "./actions";import type{CommentRow}from "./schema";
import {CommentUpvoteButton} from "./comment-upvote-button";
type Page={items:CommentRow[];nextCursor:string|null};const dateFormatter=new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"});
export function CommentsSection({questionId,hideHeading=false,compactComposer=false}:{questionId:string;hideHeading?:boolean;compactComposer?:boolean}){
 const[items,setItems]=useState<CommentRow[]>([]);const[cursor,setCursor]=useState<string|null|undefined>(undefined);const[status,setStatus]=useState<"loading"|"ready"|"error">("loading");const[actionState,setActionState]=useState<CommentActionState|null>(null);const[posting,startPosting]=useTransition();const loading=useRef(false);
 const load=useCallback(async(next?:string|null)=>{if(loading.current||next===null)return;loading.current=true;setStatus("loading");try{const response=await fetch(`/api/questions/${questionId}/comments${next?`?cursor=${encodeURIComponent(next)}`:""}`);if(!response.ok)throw new Error();const page=await response.json() as Page;setItems((current)=>next?[...current,...page.items]:page.items);setCursor(page.nextCursor);setStatus("ready")}catch{setStatus("error")}finally{loading.current=false}},[questionId]);
 useEffect(()=>{
  // Comments are intentionally fetched separately from the question/feed payload.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load();
 },[load]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);startPosting(async()=>{try{const response=await fetch(`/api/questions/${questionId}/comments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:data.get("body")})});const result=await response.json() as CommentActionState;setActionState(result);if(response.ok&&result.comment){setItems((current)=>[result.comment!,...current.filter((item)=>item.comment_id!==result.comment!.comment_id)]);form.reset()}}catch{setActionState({status:"error",message:"Connexion impossible. Réessayez."})}})}
 function addReaction(emoji:string){const field=document.getElementById(`comment-${questionId}`);if(!(field instanceof HTMLTextAreaElement))return;field.value=`${field.value}${emoji}`.slice(0,300);field.dispatchEvent(new Event("input",{bubbles:true}))}
 const composer=<form onSubmit={submit} className={compactComposer?"comment-composer":"mt-4"}><input type="hidden" name="questionId" value={questionId}/>{compactComposer?<div className="comment-reactions" aria-label="Réactions rapides">{["😂","🥰","😭","😮","😉","😅","🥺"].map((emoji)=><button key={emoji} type="button" onClick={()=>addReaction(emoji)} aria-label={`Ajouter ${emoji}`}>{emoji}</button>)}</div>:null}<label htmlFor={`comment-${questionId}`} className={compactComposer?"sr-only":"field-label"}>Votre commentaire</label><div className={compactComposer?"comment-composer-row":""}><span className={compactComposer?"comment-avatar":"hidden"} aria-hidden="true">E</span><textarea id={`comment-${questionId}`} name="body" required maxLength={300} rows={compactComposer?1:4} placeholder={compactComposer?"Ajouter un commentaire…":undefined} className={compactComposer?"comment-composer-input":"field-input min-h-28 py-3"} aria-describedby={compactComposer?undefined:`comment-help-${questionId}`}/>{compactComposer?<button className="comment-send-button" disabled={posting} aria-label="Publier le commentaire">{posting?"…":"↑"}</button>:null}</div>{compactComposer?null:<div className="mt-2 flex items-center justify-between gap-3"><p id={`comment-help-${questionId}`} className="text-xs text-[var(--muted)]">300 caractères maximum, sans lien ni coordonnées.</p><button className="primary-button compact" disabled={posting}>{posting?"Publication…":"Publier"}</button></div>}{actionState?<p role={actionState.status==="error"?"alert":"status"} className={actionState.status==="error"?"field-error":"mt-2 text-sm text-green-800"}>{actionState.message}</p>:null}</form>;
 return <section id={`comments-${questionId}`} className={hideHeading?"comments-sheet-section":"mt-6 scroll-mt-6 border-t border-black/10 pt-6"} aria-labelledby={hideHeading?undefined:`comments-title-${questionId}`}>{hideHeading?null:<><h2 id={`comments-title-${questionId}`} className="text-xl font-bold">Commentaires</h2><p className="mt-1 text-sm text-[var(--muted)]">Discussion sans réponses imbriquées.</p></>}
  {compactComposer?null:composer}
  <div className={compactComposer?"":"mt-6"}>{status==="loading"&&!items.length?<p role="status">Chargement des commentaires…</p>:null}{status==="error"&&!items.length?<div className="error-state" role="alert"><p>Impossible de charger les commentaires.</p><button className="secondary-button compact mt-3" onClick={()=>void load()}>Réessayer</button></div>:null}{status==="ready"&&!items.length?<div className="empty-state">Aucun commentaire. Soyez la première personne à contribuer.</div>:null}
   {items.length?<ul className={compactComposer?"comment-thread":"space-y-3"}>{items.map((comment)=><li key={comment.comment_id} className={compactComposer?"comment-row":"rounded-2xl border border-black/10 p-4"}><div className={compactComposer?"comment-row-avatar":"hidden"} aria-hidden="true">{comment.author_username.slice(0,1).toUpperCase()}</div><div className={compactComposer?"comment-row-content":""}><p className="text-sm font-semibold">@{comment.author_username}{comment.author_verified?" · ✓":""}</p><p className={compactComposer?"mt-1 whitespace-pre-wrap text-[.92rem] leading-5":"mt-2 whitespace-pre-wrap leading-6"}>{comment.body}</p><div className={compactComposer?"comment-row-meta":"mt-3 flex flex-wrap items-start gap-2"}><time className="text-xs text-[var(--muted)]" dateTime={comment.created_at}>{dateFormatter.format(new Date(comment.created_at))}</time><CommentUpvoteButton commentId={comment.comment_id} initiallyUpvoted={comment.is_upvoted} initialCount={comment.upvote_count} compact={compactComposer}/><ReportForm targetType="comment" targetId={comment.comment_id} label="Signaler"/></div></div></li>)}</ul>:null}
   {status==="error"&&items.length?<p className="field-error" role="alert">Les commentaires suivants n’ont pas pu être chargés.</p>:null}{cursor?<button className="secondary-button mt-4 w-full" onClick={()=>void load(cursor)} disabled={status==="loading"}>{status==="loading"?"Chargement…":"Afficher plus de commentaires"}</button>:null}
  </div>{compactComposer?composer:null}</section>;
}
