"use client";import{useActionState,useState,type FormEvent}from"react";import{decideAutomatedQuestion,moderateQuestionDirectly,setForbiddenTerm,setQuickVerification,setSuspension,setVerification,type ModerationState}from"./actions";
const initial={status:"idle",message:""} satisfies ModerationState;
export function SuspensionForm({userId,suspended}:{userId:string;suspended:boolean}){const[state,action,pending]=useActionState(setSuspension,initial);return <form action={action} className="mt-4 space-y-3"><input type="hidden" name="userId" value={userId}/><input type="hidden" name="suspended" value={String(!suspended)}/><label className="field-label" htmlFor="suspensionReason">Justification</label><textarea className="field-input min-h-20 py-3" id="suspensionReason" name="reason" required minLength={5}/><button className="secondary-button" disabled={pending}>{suspended?"Réactiver":"Suspendre"}</button>{state.message?<p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"field-error":"text-sm text-green-800"}>{state.message}</p>:null}</form>}
export function VerificationForm({userId}:{userId:string}){const[state,action,pending]=useActionState(setVerification,initial);return <form action={action} className="mt-5 grid gap-3"><input type="hidden" name="userId" value={userId}/><label className="field-label">Décision<select className="field-input mt-2" name="status"><option value="verified">Vérifier</option><option value="rejected">Rejeter</option><option value="pending">En attente</option></select></label><label className="field-label">Type d’organisation<input className="field-input mt-2" name="organisationType" required/></label><label className="field-label">Nom public<input className="field-input mt-2" name="organisationName" required/></label><label className="field-label">Description publique<textarea className="field-input mt-2 min-h-20 py-3" name="publicDescription" maxLength={500}/></label><label className="field-label">Site officiel privé<input className="field-input mt-2" name="officialWebsite" type="url"/></label><label className="field-label">Responsable privé<input className="field-input mt-2" name="responsibleOwner"/></label><label className="field-label">Notes privées<textarea className="field-input mt-2 min-h-20 py-3" name="privateNotes"/></label><button className="primary-button" disabled={pending}>Enregistrer la vérification</button>{state.message?<p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"field-error":"text-sm text-green-800"}>{state.message}</p>:null}</form>}
export function ForbiddenTermForm(){const[state,action,pending]=useActionState(setForbiddenTerm,initial);return <form action={action} className="mt-4 flex flex-wrap items-end gap-3"><label className="field-label flex-1">Terme<input className="field-input mt-2" name="term" required/></label><label className="field-label">Sévérité<select className="field-input mt-2" name="severity"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><input type="hidden" name="active" value="true"/><button className="primary-button" disabled={pending}>Ajouter</button>{state.message?<p className={state.status==="error"?"field-error":"text-sm text-green-800"}>{state.message}</p>:null}</form>}
export function ForbiddenTermToggle({term,severity,active}:{term:string;severity:number;active:boolean}){const[state,action,pending]=useActionState(setForbiddenTerm,initial);return <form action={action} className="inline"><input type="hidden" name="term" value={term}/><input type="hidden" name="severity" value={severity}/><input type="hidden" name="active" value={String(!active)}/><button className="text-xs font-semibold underline" disabled={pending}>{active?"Désactiver":"Activer"}</button>{state.status==="error"?<span className="field-error" role="alert">{state.message}</span>:null}</form>}
export function QuickVerificationForm({userId,verified}:{userId:string;verified:boolean}){const[state,action,pending]=useActionState(setQuickVerification,initial);return <form action={action} className="mt-4"><input type="hidden" name="userId" value={userId}/><input type="hidden" name="verified" value={String(!verified)}/><button className={verified?"secondary-button":"primary-button"} disabled={pending}>{verified?"Retirer la certification":"Certifier immédiatement"}</button>{state.message?<p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"field-error":"mt-2 text-sm text-green-800"}>{state.message}</p>:null}</form>}
export function AdminQuestionControls({questionId,featured=false}:{questionId:string;featured?:boolean}){const[state,action,pending]=useActionState(moderateQuestionDirectly,initial);return <details className="admin-question-controls"><summary><span aria-hidden="true">✦</span> Admin</summary><form action={action} className="mt-3 grid gap-2"><input type="hidden" name="questionId" value={questionId}/><label className="field-label">Justification<textarea className="field-input mt-2 min-h-18 py-2" name="reason" required minLength={5} defaultValue="Décision éditoriale Ekoa"/></label><div className="flex flex-wrap gap-2"><button name="action" value="remove" className="secondary-button compact" disabled={pending}>Retirer</button>{featured?<button name="action" value="unfeature" className="secondary-button compact" disabled={pending}>Arrêter la mise en avant</button>:<><button name="action" value="feature_24" className="primary-button compact" disabled={pending}>Mettre en avant 24 h</button><button name="action" value="feature_48" className="primary-button compact" disabled={pending}>Mettre en avant 48 h</button></>}</div>{state.message?<p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"field-error":"text-sm text-green-800"}>{state.message}</p>:null}</form></details>}

type AutomatedDecision="approve_as_is"|"false_positive"|"approve_suggested_rewrite"|"approve_manual_edit"|"request_rewrite"|"reject";

export function AutomatedModerationDecisionForm({questionId,text,options,hasSuggestedRewrite}:{questionId:string;text:string;options:string[];hasSuggestedRewrite:boolean}){
 const[state,action,pending]=useActionState(decideAutomatedQuestion,initial);
 const[decision,setDecision]=useState<AutomatedDecision>("approve_as_is");
 const[warningLevel,setWarningLevel]=useState(0);
 const needsReason=decision==="request_rewrite"||decision==="reject";
 function confirmSensitiveDecision(event:FormEvent<HTMLFormElement>){
  if((decision==="reject"||warningLevel>0)&&!window.confirm(warningLevel>0?`Confirmer la décision et l’avertissement de niveau ${warningLevel} ?`:"Confirmer le refus de cette question ?"))event.preventDefault();
 }
 return <form action={action} onSubmit={confirmSensitiveDecision} className="mt-5 space-y-4 rounded-2xl bg-[var(--background)] p-4">
  <input type="hidden" name="questionId" value={questionId}/>
  <label className="field-label">Décision
   <select className="field-input mt-2" name="decision" value={decision} onChange={event=>{const value=event.target.value as AutomatedDecision;setDecision(value);if(!["request_rewrite","reject"].includes(value))setWarningLevel(0)}}>
    <option value="approve_as_is">Valider telle quelle</option>
    <option value="false_positive">Faux positif</option>
    <option value="approve_suggested_rewrite" disabled={!hasSuggestedRewrite}>Valider la réécriture suggérée</option>
    <option value="approve_manual_edit">Modifier manuellement et publier</option>
    <option value="request_rewrite">Demander une réécriture</option>
    <option value="reject">Refuser</option>
   </select>
  </label>
  {decision==="approve_manual_edit"?<fieldset className="space-y-3"><legend className="font-bold">Version à publier</legend><label className="field-label">Question<textarea className="field-input mt-2 min-h-24 py-3" name="text" defaultValue={text} required minLength={10} maxLength={180}/></label>{options.map((option,index)=><label key={index} className="field-label">Réponse {index+1}<input className="field-input mt-2" name="options" defaultValue={option} required maxLength={80}/></label>)}</fieldset>:null}
  {needsReason?<label className="field-label">Raison communiquée à l’auteur<textarea className="field-input mt-2 min-h-24 py-3" name="reason" required minLength={5} maxLength={500}/></label>:<input type="hidden" name="reason" value=""/>}
  {needsReason?<label className="field-label">Avertissement
   <select className="field-input mt-2" name="warningLevel" value={warningLevel} onChange={event=>setWarningLevel(Number(event.target.value))}>
    <option value="0">Aucun avertissement</option><option value="1">Niveau 1 — rappel des règles</option>{decision==="reject"?<><option value="2">Niveau 2 — avertissement sérieux</option><option value="3">Niveau 3 — avertissement grave</option></>:null}
   </select>
  </label>:<input type="hidden" name="warningLevel" value="0"/>}
  <button className={decision==="reject"?"secondary-button w-full":"primary-button w-full"} disabled={pending}>{pending?"Enregistrement…":"Confirmer la décision"}</button>
  {state.message?<p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"field-error":"text-sm font-semibold text-green-800"}>{state.message}</p>:null}
 </form>;
}
