import{describe,expect,it}from"vitest";
import{loadCoreModerationLexicon,loadExtendedModerationLexicon,loadFullModerationLexicon}from"./server/lexicon-loader";

const normalized=(value:string)=>value.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLocaleLowerCase("fr");

describe("lexiques de modération français",()=>{
 it("charge et met en cache les trois fichiers",async()=>{const[firstFull,secondFull,firstCore,secondCore,firstExtended,secondExtended]=await Promise.all([loadFullModerationLexicon(),loadFullModerationLexicon(),loadCoreModerationLexicon(),loadCoreModerationLexicon(),loadExtendedModerationLexicon(),loadExtendedModerationLexicon()]);expect(firstFull).toBe(secondFull);expect(firstCore).toBe(secondCore);expect(firstExtended).toBe(secondExtended)});
 it("valide les volumes et statistiques",async()=>{const[full,core,extended]=await Promise.all([loadFullModerationLexicon(),loadCoreModerationLexicon(),loadExtendedModerationLexicon()]);expect(core.terms).toHaveLength(1584);expect(extended.terms).toHaveLength(1910);expect(full.terms).toHaveLength(3494);expect(full.statistics.canonical_terms).toBe(full.terms.length);expect(full.statistics.variants).toBe(full.terms.reduce((total,term)=>total+term.variants.length,0));expect(full.statistics.expressions).toBe(full.expressions.length);expect(full.statistics.patterns).toBe(full.patterns.length);expect(full.statistics.test_cases).toBe(full.test_cases.length);expect(full.statistics.risk_categories).toBe(full.risk_categories.length);expect(full.statistics.regex_errors).toBe(0)});
 it("compile tous les motifs regex",async()=>{const full=await loadFullModerationLexicon();expect(()=>full.patterns.forEach(pattern=>new RegExp(pattern.regex,pattern.flags.join("")))).not.toThrow()});
 it("interdit aux termes extended d’agir seuls",async()=>{const extended=await loadExtendedModerationLexicon();expect(extended.terms.every(term=>term.tier==="extended"&&!term.trigger_on_term_alone&&term.trigger_policy==="monitor_only"&&term.recommended_action==="CONTEXT_ONLY")).toBe(true)});
 it("valide les variantes sensibles de référence",async()=>{const core=await loadCoreModerationLexicon();const byTerm=new Map(core.terms.map(term=>[term.term,term]));expect(byTerm.get("bâtard")?.variants.map(normalized)).toContain("batard");expect(byTerm.get("bicot")?.variants).toContain("biko");expect(byTerm.get("nègre")?.variants.map(normalized)).toEqual(expect.arrayContaining(["negre","negresse"]));expect(["ambiguous","dependent","highly_ambiguous"]).toContain(byTerm.get("gwer")?.context_dependency)});
 it("valide les contextes et suggestions autorisés",async()=>{const core=await loadCoreModerationLexicon();const byTerm=new Map(core.terms.map(term=>[term.term,term]));expect(byTerm.get("chienne")?.allowed_contexts).toEqual(expect.arrayContaining(["animal","chien"]));expect(byTerm.get("pisse")?.replacement_suggestions).toContain("urine");expect(byTerm.get("ordures")?.allowed_contexts).toEqual(expect.arrayContaining(["déchets","recyclage"]))});
});
