import{readFileSync}from"node:fs";import{describe,expect,it,vi}from"vitest";
import{moderateQuestion}from"./server";
import{loadExtendedModerationLexicon}from"./server/lexicon-loader";

describe("moteur contextuel de modération Ekoa",()=>{
 it("distingue le contexte animal et propose une réécriture",async()=>{const result=await moderateQuestion("Combien de fois votre chienne pisse contre les ordures pendant sa promenade ?");expect(result.action).toBe("REVIEW");expect(result.targetType).toBe("animal");expect(result.predictedSeverity).toBeLessThanOrEqual(1);expect(result.detectedTerms.map(term=>term.canonicalTerm)).toEqual(expect.arrayContaining(["chienne","pisse","ordures"]));expect(result.suggestedRewrite).not.toBeNull()},15000);
 it("autorise le contexte animal tout en gardant le terme core en review",async()=>{const result=await moderateQuestion("Votre chienne aime-t-elle les longues promenades ?");expect(result.action).toBe("REVIEW");expect(result.targetType).toBe("animal");expect(result.predictedSeverity).toBe(0)});
 it("reconnaît une insulte visant une personne",async()=>{const result=await moderateQuestion("Cette femme est-elle une chienne ?");expect(result.action).toBe("REVIEW");expect(result.targetType).toBe("person");expect(result.predictedSeverity).toBe(2)});
 it("distingue les déchets d’une cible humaine",async()=>{const waste=await moderateQuestion("Faut-il améliorer le ramassage des ordures ?");const group=await moderateQuestion("Ces personnes sont-elles des ordures ?");expect(waste.action).toBe("REVIEW");expect(waste.targetType).toBe("waste");expect(waste.predictedSeverity).toBe(0);expect(group.action).toBe("REVIEW");expect(group.targetType).toBe("group");expect(group.predictedSeverity).toBe(2)});
 it("réduit le suicide préventif et bloque l’encouragement",async()=>{const prevention=await moderateQuestion("Faut-il renforcer la prévention du suicide ?");const attack=await moderateQuestion("Va te suicider");expect(prevention.contextCodes).toContain("PREVENTIVE_CONTEXT");expect(prevention.predictedSeverity).toBe(0);expect(attack.action).toBe("BLOCK_RECOMMENDED");expect(attack.predictedSeverity).toBe(3);expect(attack.intent).toBe("self_harm_encouragement");expect(attack.detectedExpressions.length+attack.detectedPatterns.length).toBeGreaterThan(0)});
 it("distingue la prévention du terrorisme d’une glorification ambiguë",async()=>{const prevention=await moderateQuestion("Comment mieux lutter contre le terrorisme ?");const ambiguous=await moderateQuestion("Cet attentat était-il une bonne chose ?");expect(prevention.predictedSeverity).toBe(0);expect(prevention.contextCodes).toContain("PREVENTIVE_CONTEXT");expect(ambiguous.action).toBe("REVIEW");expect(ambiguous.contextCodes).toContain("POSSIBLE_GLORIFICATION");expect(ambiguous.predictedSeverity).toBeGreaterThanOrEqual(1)});
 it("laisse passer une question neutre",async()=>{const result=await moderateQuestion("Cette question est parfaitement neutre.");expect(result.action).toBe("ALLOW");expect(result.predictedSeverity).toBe(0);expect(result.detectedTerms).toHaveLength(0);expect(result.detectedExpressions).toHaveLength(0);expect(result.detectedPatterns).toHaveLength(0)});
 it.each([["batard","bâtard"],["bâtard","bâtard"],["b4tard","bâtard"],["biko","bicot"],["nègre","nègre"],["negr0","negro"],["n e g r o","negro"],["s@lope","salope"],["ordur3s","ordures"],["ch1enne","chienne"],["saaalope","salope"],["p.é.d.é","pédé"]])("détecte la variante %s comme %s",async(input,canonical)=>{const result=await moderateQuestion(`Est-ce acceptable de dire ${input} ?`);expect(result.detectedTerms.map(term=>term.canonicalTerm)).toContain(canonical)});
 it("ignore une correspondance partielle dans un mot plus long",async()=>{const result=await moderateQuestion("Cette classification est parfaitement ordinaire.");expect(result.detectedTerms.some(term=>term.canonicalTerm==="rat")).toBe(false)});
 it("détecte un pseudonyme et un groupe protégé",async()=>{expect((await moderateQuestion("@pseudo est un connard ?")).targetType).toBe("username");expect((await moderateQuestion("Les musulmans sont-ils des ordures ?")).targetType).toBe("protected_group")});
 it("reconnaît les contextes médical et historique neutres",async()=>{const medical=await moderateQuestion("Comment améliorer le traitement médical après une tentative de suicide ?");const historical=await moderateQuestion("Comment enseigner l'histoire du terrorisme ?");expect(medical.predictedSeverity).toBe(0);expect(medical.contextCodes).toContain("MEDICAL_CONTEXT");expect(historical.predictedSeverity).toBe(0);expect(historical.contextCodes).toContain("INFORMATIVE_CONTEXT")});
 it("bloque menace, doxxing et appel à la violence",async()=>{for(const text of["Je vais te tuer","Voici son adresse : 10 rue de Paris","Mort aux musulmans"]){const result=await moderateQuestion(text);expect(result.action).toBe("BLOCK_RECOMMENDED");expect(result.predictedSeverity).toBe(3)}});
 it("un terme extended seul reste en surveillance et est autorisé",async()=>{const lexicon=await loadExtendedModerationLexicon();const term=lexicon.terms.find(entry=>entry.term.length>5)!;const result=await moderateQuestion(`Que signifie ${term.term} ?`);expect(result.detectedTerms.some(entry=>entry.tier==="extended")).toBe(true);expect(result.action).toBe("ALLOW")});
 it("est déterministe et préserve le texte original",async()=>{const text="Votre chienne aime les promenades ?";const[first,second]=await Promise.all([moderateQuestion(text),moderateQuestion(text)]);expect(first).toEqual(second);expect(text).toBe("Votre chienne aime les promenades ?")});
 it("ne contient aucun branchement réseau, Supabase ou écriture",()=>{const files=["normalize-text.ts","lexical-detector.ts","expression-detector.ts","pattern-detector.ts","target-detector.ts","context-analyzer.ts","severity-evaluator.ts","rewrite-suggester.ts","decision-engine.ts","moderate-question.ts"].map(file=>readFileSync(`src/features/moderation/server/${file}`,"utf8")).join("\n");expect(files).not.toMatch(/supabase|fetch\(|axios|insert\(|update\(|delete\(|warning|notification/i);expect(vi.isMockFunction(moderateQuestion)).toBe(false)});
});
